spring:
  profiles:
    active: dev
  datasource:
    username: visitor
    password: mysql@irbl
    url: jdbc:mysql://101.132.253.222/irbl?serverTimezone=CTT&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #password: fill it in application-dev.yml
    timeout: 1000
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

server:
  port: 40000