apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: IRBL
  name: IRBL
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IRBL
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: IRBL
    spec:
      containers:
      - image: 101.132.148.43/backend/IMAGE:{VERSION}
        name: IRBL
      imagePullSecrets:
        - name: admin
---
apiVersion: v1
kind: Service
metadata:
  name: IRBL
  namespace: admin
  labels:
    app: IRBL
spec:
  type: NodePort
  selector:
    app: IRBL
  ports:
  - name: tcp
    nodePort: 40000
    protocol: TCP
    port: 9090
    targetPort: 9090
